bcgov/gwa-api

- microservices/gatewayApi/clients/kong.py
- microservices/gatewayApi/clients/ocp_networksecuritypolicy.py
- microservices/gatewayApi/entrypoint.sh
- microservices/gatewayApi/templates/keycloak/client.json
- microservices/gatewayApi/v1/routes/gw_status.py
- microservices/gatewayApi/v1/routes/namespaces.py
- microservices/gatewayApi/v1/spec/v1.yaml
- microservices/gatewayApi/v1/v1.py
> Add status check of upstream service

- USER-JOURNEY.md
- docs/OCP4-MIGRATION.md
- docs/samples/service-plugins/service-jwt-keycloak.yaml
- microservices/gatewayApi/clients/kong.py
- microservices/gatewayApi/v1/routes/gw_status.py
> Fix status results

- README.md
- USER-JOURNEY.md
- microservices/gatewayApi/app.py
- microservices/gatewayApi/auth/token.py
- microservices/gatewayApi/clients/ocp_routes.py
- microservices/gatewayApi/v1/routes/dns.py
- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v1/routes/namespaces.py
- microservices/gatewayApi/v1/services/namespaces.py
- microservices/gatewayApi/v1/spec/v1.yaml
- microservices/gatewayApi/v1/v1.py
> Host validation and postman support

- microservices/gatewayApi/v1/routes/gateway.py
> Minor release

- USER-JOURNEY.md
- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/app.py
- microservices/gatewayApi/v1/routes/gateway.py
> Support for Gateway Certs and CaCerts

- microservices/gatewayApi/v2/routes/gateway.py
> Skip OCP Route Updates for Local Environment Work

- microservices/gatewayApi/clients/portal.py
- microservices/gatewayApi/v2/routes/consumers.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayApi/v2/services/gateway_consumers.py
- microservices/gatewayApi/v2/v2.py
> Add Consumer Service for Managing Consumers and Plugins

- microservices/gatewayApi/utils/transforms.py
> Added support to accept deduplicate plugin configuration for rate limiting plugin

- microservices/gatewayApi/clients/kong.py
- microservices/gatewayApi/clients/portal.py
- microservices/gatewayApi/v2/routes/consumers.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayApi/v2/routes/migrate_v1.py
- microservices/gatewayApi/v2/services/gateway_consumers.py
- microservices/gatewayApi/v2/v2.py
> Plugin updates for Consumer and de-duplicated config

- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
> Improved the logging to identify the data plane

- microservices/gatewayJobScheduler/main.py
> updated get_routes function to support paging and fetch all the routes

- microservices/gatewayJobScheduler/main.py
> added fix to loop through route hosts to create independent records

- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
Currently gwa-api does not validate the configFile and it deletes all the services and routes for the namespace. 
Fixes #58
> Added validations for configfile to ensure it is not empty or null

- .github/workflows/dev.yml
- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/kubeApi/Dockerfile
- microservices/kubeApi/clients/ocp_routes.py
Fixes https://dpdd.atlassian.net/browse/APS-937
> KubeAPI: Code Optimization to Reduce the Response Time

- README.md
> creating a dummy commit for new release

- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/requirements.txt
- microservices/gatewayApi/v2/routes/consumers.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayApi/v2/routes/gw_status.py
- microservices/gatewayApi/v2/routes/migrate_v1.py
- microservices/gatewayApi/v2/routes/namespaces.py
- microservices/gatewayApi/v2/routes/whoami.py
Fixes https://app.zenhub.com/workspaces/bc-gov-api-services-60943b8bf73eb300102d9c97/issues/bcgov/api-services-portal/335
> Bumped up Flask and Jinja2 version to fix issue with markupsafe update

- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/requirements.txt
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayJobScheduler/Dockerfile
- microservices/kubeApi/Dockerfile
Resolves security vulnerabilities.
- Updates Dockerfiles in `gatewayAPi`, `gatewayJobScheduler`, and `kubeApi` to use `python:3.8.13-alpine3.15`
- Updates `gatewayApi/requirements.txt` to use `PyYAML==5.4`.
> Updates images, python requirements

- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/clients/portal.py
- microservices/gatewayJobScheduler/Dockerfile
- microservices/kubeApi/Dockerfile
> Image upgrade and validation fix

- microservices/gatewayApi/clients/portal.py
- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayApi/v2/routes/namespaces.py
* Deleting a namespace is giving an error in production - this resolves that error
* Cleanup of the Activity logging
* Fixes #75
> Fix Failed NS deletion and better Activity

- microservices/gatewayApi/requirements.txt
> Update PyYAML version from 5.4 to 6.0.1

- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/app.py
- microservices/gatewayApi/clients/portal.py
- microservices/gatewayApi/requirements.txt
- microservices/gatewayApi/swagger.py
- microservices/gatewayApi/v3/auth/auth.py
- microservices/gatewayApi/v3/routes/gateway.py
- microservices/gatewayApi/v3/routes/gw_status.py
- microservices/gatewayApi/v3/routes/whoami.py
- microservices/gatewayApi/v3/spec/spec.yaml
- microservices/gatewayApi/v3/v3.py
- microservices/gatewayApi/wsgi.py
> Support a v3 with latest deck

- microservices/gatewayApi/entrypoint.sh
- microservices/gatewayApi/utils/transforms.py
* allow overrides for upstream jwt plugin
* add upstream config in the entrypoint
* upd upstream jwt issuer default
> kong upstream jwt plugin defaults (#107)

- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayApi/v3/routes/gateway.py
* upd ca certs entity
* only allow privileged ns for ca certs
> limit use of ca_certificates (#109)

- microservices/gatewayApi/tests/routes/v2/test_gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
> fix for validating ca_certificates

- microservices/kubeApi/templates/v1/services.py
> use data-plane as service selector match

- microservices/gatewayApi/Dockerfile
- microservices/gatewayApi/config/test.json
- microservices/gatewayApi/entrypoint.sh
- microservices/gatewayApi/tests/routes/v2/test_gateway.py
- microservices/gatewayApi/tests/utils/test_add_version.py
- microservices/gatewayApi/utils/deck.py
- microservices/gatewayApi/utils/transforms.py
- microservices/gatewayApi/v1/routes/gateway.py
- microservices/gatewayApi/v2/routes/gateway.py
- microservices/gatewayApi/v2/routes/namespaces.py
- update to the latest version of `deck` `1.45.0`
- make deck version configurable with `DECK_CLI` environment variable
> Feature upgrade deck

- microservices/gatewayJobScheduler/app.py
- microservices/gatewayJobScheduler/tests/test_get_certificate.py
- microservices/gatewayJobScheduler/tests/test_transform_data_by_ns.py
* Continue if matching certificate by SNI not found
* Aidan's fix suggestion
* Fix comment and formatting
* Couple other fixes
* Update cert snis format for testing
* try simpler fix again
> Feature/scheduler fix (#213)
